services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build: ./Docker/Nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
